version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.0
  cli: digitalocean/cli@0.1.1
  docker: circleci/docker@1.0.0

defaults: &defaults
  working_directory: ~/repo

jobs:
  test-web:
    <<: *defaults
    docker:
      - image: node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "web/package.json" }}
            - v1-dependencies-
      - run: yarn --cwd web install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "web/package.json" }}
      - run: yarn --cwd web test
      - persist_to_workspace:
          root: ~/repo
          paths: .

  build-web:
    <<: *defaults
    docker:
      - image: node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "web/package.json" }}
            - v1-dependencies-
      - run: yarn --cwd web install
      - run: yarn --cwd web build
      - persist_to_workspace:
          root: ~/repo
          paths: .

  test-server:
    <<: *defaults
    docker:
      - image: node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            - v1-dependencies-
      - run: yarn --cwd server install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}
      - run: yarn --cwd server test

  build-server:
    <<: *defaults
    docker:
      - image: node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            - v1-dependencies-
      - run: yarn --cwd server build
workflows:
  build-and-test:
    jobs:
      - test-web
      - test-server
      - build-web:
          requires:
            - test-web
          filters:
            branches:
              only:
                - master
      - docker/publish:
          working_directory: ~/repo
          executor: docker/docker
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          lint-dockerfile: true
          tag: $CIRCLE_SHA1,latest
          before_build:
            - attach_workspace:
                at: ~/repo
            - run: ls web
            - run: ls server
          requires:
            - build-web
            - build-server
          filters:
            branches:
              only:
                - master
