version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.0
  cli: digitalocean/cli@0.1.1
  docker: circleci/docker@1.0.0

defaults: &defaults
  working_directory: ~/repo

jobs:
  web-test:
    <<: *defaults
    docker:
      - image: node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "web/package.json" }}
            - v1-dependencies-
      - run: yarn --cwd web install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "web/package.json" }}
      - run: yarn --cwd web test
      - persist_to_workspace:
          root: ~/repo
          paths: .

  web-build:
    <<: *defaults
    docker:
      - image: node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "web/package.json" }}
            - v1-dependencies-
      - run: yarn --cwd web install
      - run: yarn --cwd web build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - web/build

  server-test:
    <<: *defaults
    docker:
      - image: node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            - v1-dependencies-
      - run: yarn --cwd server install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}
      - run: yarn --cwd server test

  server-build:
    <<: *defaults
    docker:
      - image: node:13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            - v1-dependencies-
      - run: npm i -g typescript
      - run: yarn --cwd server
      - run: yarn --cwd server build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - server/build

    docker-build-and-push:
      <<: *defaults
      executor: docker/docker
      steps:
        - setup_remote_docker
        - checkout
        - attach_workspace:
          at: ~/repo
        - docker/check
        - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1,latest

workflows:
  install-and-test:
    jobs:
      - docker-build-and-push
      # - web-test
      # - server-test
      # - server-build:
      #     requires:
      #       - web-test
      #     filters:
      #       branches:
      #         only:
      #           - master
      # - web-build:
      #     requires:
      #       - web-test
      #     filters:
      #       branches:
      #         only:
      #           - master
