version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.0
  cli: digitalocean/cli@0.1.1
  docker: circleci/docker@1.0.0

jobs:
  test-web:
    docker:
      - image: node:13
    steps:
      - checkout
      - run: yarn --cwd web install
      - run: yarn --cwd web test
      - persist_to_workspace:
          root: .
          paths: .

  build-web:
    docker:
      - image: node:13
    steps:
      - attach_workspace
      - run: yarn --cwd web build
      - persist_to_workspace:
          root: .
          paths: .

  test-server:
    docker:
      - image: node:13
    steps:
      - checkout
      - run: yarn --cwd server install
      - run: yarn --cwd server test

workflows:
  build-and-test:
    jobs:
      - test-web
      - test-server
      - build-web:
          requires:
            - test-web
          filters:
            branches:
              only:
                - master
      # - docker/publish:
      #     executor: docker/docker
      #     image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      #     lint-dockerfile: true
      #     tag: $CIRCLE_SHA1,latest
      #     before_build:
      #       - attach_workspace
      #     requires:
      #       - build-web
      #       - test-server
      #     filters:
      #       branches:
      #         only:
      #           - master
