version: 2.1

jobs:
  test-web:
    docker:
      - image: node:13
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn --cwd web install
      - run: yarn --cwd web test
      - persist_to_workspace:
          root: .
          paths: .

  build-web:
    docker:
      - image: node:13
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run: yarn --cwd web build

  test-server:
    docker:
      - image: node:13
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn --cwd server install
      - run: yarn --cwd server test

  deploy-docker:
    working_directory: ~/app
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/app
      - run: docker login -u florianherrengt -p $DOCKER_TOKEN
      - run: docker build -t florianherrengt/scramblr:${CIRCLE_SHA1} ./server
      - run: docker push florianherrengt/scramblr:${CIRCLE_SHA1}

workflows:
  build-and-test:
    jobs:
      - test-web
      - test-server
      - build-web:
          requires:
            - test-web
          filters:
            branches:
              only:
                - master
      - deploy-docker:
          requires:
            - test-server
          filters:
            branches:
              only:
                - master
