version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.0
  cli: digitalocean/cli@0.1.1

jobs:
  test-web:
    docker:
      - image: node:13
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn --cwd web install
      - run: yarn --cwd web test
      - persist_to_workspace:
          root: .
          paths: .

  build-web:
    docker:
      - image: node:13
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run: yarn --cwd web build
      - persist_to_workspace:
          root: .
          paths: . 

  test-server:
    docker:
      - image: node:13
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn --cwd server install
      - run: yarn --cwd server test

  build-and-push-docker:
    executor: docker/docker
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/app
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          lint-dockerfile: true
          tag: $CIRCLE_SHA1,latest

workflows:
  build-and-test:
    jobs:
      - test-web
      - test-server
      - build-web:
          requires:
            - test-web
          filters:
            branches:
              only:
                - master
      - build-and-push-docker:
          requires:
            - build-web
            - test-server
          filters:
            branches:
              only:
                - master
