kind: pipeline
type: kubernetes
name: scramblr_node_api

metadata:
  namespace: drone

steps:
  - name: greeting
    image: node:13
    commands:
      - echo hello
      - echo world
      - echo test
